---
# defaults
jumpstarter_helm_repo: "quay.io/jumpstarter-dev/helm"
jumpstarter_helm_repo_version: "0.7.1" # see https://quay.io/repository/jumpstarter-dev/jumpstarter-controller for available versions

# qemu exporter count
jumpstarter_qemu_exporter_count: 2

# gitops namespace
gitops_namespace: "openshift-gitops" # namespace of the cluster gitops instance
