# Implement your post-install deployment tasks here
# -------------------------------------------------


# cleanup temp files

- name: remove the htpasswd file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "roles/setup-auth/files/users.htpasswd"