---
# Default values for the config-cluster role. To override, add them to the inventory file (main.yml).

#------------------------------------------------------------------------------------------------
# aws defaults
#------------------------------------------------------------------------------------------------

# secondary set of compute nodes (arm64)
aws_arm_instance_type: "m8g.xlarge" # 4 vCPU, 16 GiB RAM
aws_arm_ami_id: "ami-02f30107e3441227b" # ARM, us-east-2
#aws_arm_ami_id: "ami-0ba6941055f037421" # ARM, eu-west-1
#aws_arm_ami_id: "ami-00bd76511738f7c79" # ARM, eu-central-1

aws_arm_instance_count: 1 # number of replicas per availability zone
aws_arm_volume_size: 120
aws_arm_volume_type: "gp3"
aws_arm_vcpu: 4
aws_arm_gpu: 0
aws_arm_memory: 16384

# bare-metal worker node
aws_metal_instance_type: "m6g.metal" # 64 vCPU, 256 GiB RAM
aws_metal_availability_zone: "a" # a, b, c

aws_metal_ami_id: "ami-02f30107e3441227b" # ARM, us-east-2
#aws_metal_ami_id: "ami-0ba6941055f037421" # ARM, eu-west-1
#aws_metal_ami_id: "ami-00bd76511738f7c79" # ARM, eu-central-1

aws_metal_instance_count: 1 # number of replicas per availability zone
aws_metal_volume_size: 120
aws_metal_volume_type: "gp3"
aws_metal_vcpu: 64
aws_metal_gpu: 0
aws_metal_memory: 262144

#------------------------------------------------------------------------------------------------
# azure defaults  
#------------------------------------------------------------------------------------------------

# see https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dv5-series
# see https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dpsv5-series

# secondary set of compute nodes (arm64)
azure_arm_instance_type: "Standard_D8ps_v5" # 8 vCPU, 32 GiB RAM
azure_arm_instance_count: 1 # number of replicas per availability zone
azure_arm_volume_size: 128
azure_arm_volume_type: "Premium_LRS"
azure_arm_vcpu: 4
azure_arm_gpu: 0
azure_arm_memory: 32768

#------------------------------------------------------------------------------------------------
# gcp defaults
#------------------------------------------------------------------------------------------------

# secondary set of compute nodes (arm64)
gcp_arm_instance_type: "t2a-standard-8" # 8 vCPU, 32 GiB RAM
gcp_arm_instance_count: 2 # number of replicas per availability zone
gcp_arm_volume_size: 128
gcp_arm_volume_type: "pd-ssd"
gcp_arm_vcpu: 8
gcp_arm_gpu: 0
gcp_arm_memory: 32768

#------------------------------------------------------------------------------------------------
# cnv operator
#------------------------------------------------------------------------------------------------

cnv_operator_name: "kubevirt-hyperconverged"
cnv_operator_subscription_name: "kubevirt-hyperconverged"
cnv_operator_deployment_name: "virt-operator"
cnv_subscription_channel: "stable"
cnv_subscription_starting_csv: "kubevirt-hyperconverged-operator.v4.19.1"
cnv_operator_namespace: "openshift-cnv"
cnv_operator_group: "openshift-cnv"
